export const dogBreeds: { [key: string]: string } = {
  "Affenpinscher": "猴犬",
  "Afghan hound": "阿富汗獵犬",
  "Airedale terrier": "艾爾島梗",
  "Akita": "秋田犬",
  "Alaskan malamute": "阿拉斯加雪橇犬",
  "American staffordshire terrier": "美國斯塔福郡梗",
  "Appenzeller": "阿彭策爾牧羊犬",
  "Australian cattle dog": "澳洲牧牛犬",
  "Australian shepherd": "澳洲牧羊犬",
  "Australian terrier": "澳洲梗",
  "Basenji": "巴辛吉犬",
  "Basset hound": "巴吉度獵犬",
  "Beagle": "米格魯",
  "Bedlington terrier": "貝德靈頓梗",
  "Bernese mountain dog": "伯恩山犬",
  "Bichon frise": "比熊犬",
  "Black and tan coonhound": "黑褐獵浣熊犬",
  "Blenheim spaniel": "布萊尼姆獵犬",
  "Bloodhound": "尋血獵犬",
  "Bluetick coonhound": "藍虎紋獵浣熊犬",
  "Border collie": "邊境牧羊犬",
  "Border terrier": "邊境梗",
  "Borzoi": "俄羅斯獵狼犬",
  "Boston terrier": "波士頓梗",
  "Bouvier des flandres": "法蘭德斯牧羊犬",
  "Boxer": "拳師犬",
  "Brabancon griffon": "布魯塞爾格里芬犬",
  "Briard": "伯瑞犬",
  "Brittany spaniel": "布列塔尼獵犬",
  "Bull mastiff": "鬥牛獒",
  "Cairn terrier": "凱恩梗",
  "Cardigan welsh corgi": "卡迪根威爾士柯基犬",
  "Chesapeake bay retriever": "切薩皮克灣獵犬",
  "Chihuahua": "吉娃娃",
  "Chow chow": "鬆獅犬",
  "Clumber spaniel": "克倫伯獵犬",
  "Cocker spaniel": "可卡獵犬",
  "Collie": "柯利牧羊犬",
  "Curly-coated retriever": "捲毛尋回犬",
  "Dandie dinmont terrier": "丹第丁蒙梗",
  "Dhole": "豺",
  "Dingo": "澳洲野犬",
  "Doberman pinscher": "杜賓犬",
  "English foxhound": "英國獵狐犬",
  "English setter": "英國雪達犬",
  "English springer spaniel": "英國史賓格獵犬",
  "Entlebucher mountain dog": "恩特雷布赫山地犬",
  "Eskimo dog": "愛斯基摩犬",
  "Flat-coated retriever": "平毛尋回犬",
  "French bulldog": "法國鬥牛犬",
  "German shepherd": "德國牧羊犬",
  "German short-haired pointer": "德國短毛指示犬",
  "Giant schnauzer": "大型雪納瑞犬",
  "Golden retriever": "黃金獵犬",
  "Gordon setter": "戈登雪達犬",
  "Great dane": "大丹犬",
  "Great pyrenees": "大白熊犬",
  "Greater swiss mountain dog": "大瑞士山地犬",
  "Groenendael dog": "比利時牧羊犬",
  "Ibizan hound": "依比沙獵犬",
  "Irish setter": "愛爾蘭雪達犬",
  "Irish terrier": "愛爾蘭梗",
  "Irish water spaniel": "愛爾蘭水獵犬",
  "Irish wolfhound": "愛爾蘭獵狼犬",
  "Italian greyhound": "義大利灰狗",
  "Japanese spaniel": "日本獵犬",
  "Keeshond": "荷蘭毛獅犬",
  "Kerry blue terrier": "凱利藍梗",
  "Komondor": "匈牙利牧羊犬",
  "Kuvasz": "庫瓦茲犬",
  "Labrador retriever": "拉布拉多犬",
  "Lakeland terrier": "湖畔梗",
  "Leonberg": "萊昂貝格犬",
  "Lhasa apso": "拉薩犬",
  "Malamute": "阿拉斯加雪橇犬",
  "Malinois": "比利時瑪利諾犬",
  "Maltese": "馬爾濟斯犬",
  "Mexican hairless": "墨西哥無毛犬",
  "Miniature pinscher": "迷你杜賓",
  "Miniature poodle": "迷你貴賓犬",
  "Miniature schnauzer": "迷你雪納瑞",
  "Newfoundland dog": "紐芬蘭犬",
  "Norfolk terrier": "諾福克梗",
  "Norwegian elkhound": "挪威獵麋犬",
  "Norwich terrier": "諾威奇梗",
  "Old english sheepdog": "古代英國牧羊犬",
  "Otterhound": "水獺獵犬",
  "Papillon": "蝴蝶犬",
  "Pekinese": "北京犬",
  "Pembroke welsh corgi": "威爾士柯基犬",
  "Pomeranian": "博美犬",
  "Pug": "巴哥犬",
  "Redbone coonhound": "紅骨獵浣熊犬",
  "Rhodesian ridgeback": "羅得西亞脊背犬",
  "Rottweiler": "羅威納犬",
  "Saint bernard": "聖伯納犬",
  "Saluki": "沙魯基獵犬",
  "Samoyed": "薩摩耶犬",
  "Schipperke": "舒柏奇犬",
  "Scottish deerhound": "蘇格蘭獵鹿犬",
  "Scottish terrier": "蘇格蘭梗",
  "Sealyham terrier": "西利漢梗",
  "Shetland sheepdog": "喜樂蒂牧羊犬",
  "Shih tzu": "西施犬",
  "Siberian husky": "西伯利亞哈士奇",
  "Silky terrier": "絲毛梗",
  "Soft-coated wheaten terrier": "愛爾蘭軟毛梗",
  "Staffordshire bull terrier": "斯塔福郡鬥牛梗",
  "Standard poodle": "標準貴賓犬",
  "Standard schnauzer": "標準雪納瑞",
  "Sussex spaniel": "蘇塞克斯獵犬",
  "Tibetan mastiff": "藏獒",
  "Tibetan terrier": "西藏梗",
  "Toy poodle": "玩具貴賓犬",
  "Vizsla": "維茲拉犬",
  "Walker hound": "沃克獵犬",
  "Weimaraner": "威瑪犬",
  "Welsh springer spaniel": "威爾士史賓格獵犬",
  "West highland white terrier": "西高地白梗",
  "Whippet": "惠比特犬",
  "Wire-haired fox terrier": "硬毛獵狐梗",
  "Yorkshire terrier": "約克夏梗",
};

export function getChineseBreedName(englishName: string): string {
  const breedNames = englishName.split(', ');
  const chineseNames = breedNames.map(name => {
    const trimmedName = name.trim().toLowerCase();
    for (const [key, value] of Object.entries(dogBreeds)) {
      if (trimmedName.includes(key.toLowerCase())) {
        return value;
      }
    }
    return name; // 如果找不到對應的中文名稱，返回原始英文名稱
  });
  return chineseNames.join('、');
}